"""
Run HQGA experiments for airfoil shape optimization using XFOIL.

The script:
1. Configures the noisy quantum simulator.
2. Defines the XFOIL optimization problem.
3. Generates all HQGA parameter combinations.
4. Executes multiple independent runs for each combination.
5. Stores the relevant results for each configuration.

The experiment must be executed from the directory containing:
    - this Python script
    - run_xfoil.sh

The files eval_obj.in and eval_obj.out are generated automatically
during the execution.
"""

# =============================================================================
# Imports
# =============================================================================

from math import pi
from pathlib import Path
import os
import subprocess

import numpy as np
import pandas as pd

from qiskit_aer import AerSimulator
from qiskit_ibm_runtime.fake_provider import FakeBrisbane

from HQGA_Airfoil.problems import RealProblem
from HQGA_Airfoil import hqga_algorithm
from HQGA_Airfoil import hqga_utils


# =============================================================================
# Experiment configuration
# =============================================================================

# Current working directory.
# The experiment should be executed from the directory containing
# this script and run_xfoil.sh.
WORKING_DIR = Path.cwd()

# XFOIL files generated/used during the experiment.
XFOIL_INPUT_FILE = WORKING_DIR / "eval_obj.in"
XFOIL_OUTPUT_FILE = WORKING_DIR / "eval_obj.out"
XFOIL_SCRIPT = WORKING_DIR / "run_xfoil.sh"

# Output dataset.
RESULTS_FILENAME = "Results"

# Number of independent runs for each parameter combination.
N_RUNS = 25

# First parameter combination to execute.
# This can be changed to resume an interrupted experiment.
START_COMBINATION = 0


# =============================================================================
# HQGA parameters
# =============================================================================

BIT_LENGTHS = [5]
POPULATION_SIZES = [4]
MAX_GENERATIONS = [100]

DELTA_VALUES = [pi / 8, pi / 16]
MU_VALUES = [0.07, 0.15]
RHO_VALUES = [pi / 8, pi / 16]

ELITISM_METHODS = [
    hqga_utils.ELITISM_R,
    hqga_utils.ELITISM_Q,
    hqga_utils.ELITISM_D,
]


# =============================================================================
# XFOIL operating conditions
# =============================================================================

AIRFOIL = "NACA2412"

XFOIL_PARAMETERS = {
    "Reynolds_number": 2_500_000,
    "CL": 0.5,
    "MACH": 0.48,
    "XTRUP": 1.0,
    "XTRLO": 1.0,
    "MAX_THICK": 0.12,
}

BASELINE_AIRFOILS = {
    "NACA0012": "NACA0012.dat",
    "RAE2822": "rae2822.dat",
}

if AIRFOIL in BASELINE_AIRFOILS:
    XFOIL_PARAMETERS = {
        "BASELINE_AIRFOIL": BASELINE_AIRFOILS[AIRFOIL],
        **XFOIL_PARAMETERS,
    }

# =============================================================================
# XFOIL utilities
# =============================================================================

def write_xfoil_input(chromosome):
    """
    Generate the XFOIL input file in the current working directory.

    The file contains the fixed operating conditions of the problem
    followed by the design variables encoded in the chromosome.
    """

    with open(XFOIL_INPUT_FILE, "w") as file:

        # Write fixed operating conditions.
        for parameter, value in XFOIL_PARAMETERS.items():
            file.write(f"{parameter} = {value}\n")

        # Write chromosome variables.
        for index, value in enumerate(chromosome):
            file.write(f"X({index}) = {value}\n")


def read_xfoil_output():
    """
    Read the drag coefficient from the XFOIL output file.

    Returns
    -------
    float
        Drag coefficient CD.
    """

    if not XFOIL_OUTPUT_FILE.is_file():
        raise FileNotFoundError(
            f"'{XFOIL_OUTPUT_FILE.name}' was not generated by XFOIL."
        )

    with open(XFOIL_OUTPUT_FILE, "r") as file:
        for line in file:
            if line.startswith("CD = "):
                return float(line.split("=")[1].strip())

    raise ValueError(
        f"Could not find 'CD = ' in {XFOIL_OUTPUT_FILE.name}."
    )


def run_xfoil():
    """
    Execute run_xfoil.sh and return the drag coefficient computed by XFOIL.
    """

    if not XFOIL_SCRIPT.is_file():
        raise FileNotFoundError(
            f"'{XFOIL_SCRIPT.name}' was not found in the current "
            f"working directory: {WORKING_DIR}"
        )

    # Make the shell script executable.
    os.chmod(XFOIL_SCRIPT, 0o755)

    try:
        subprocess.run(
            ["/bin/bash", XFOIL_SCRIPT.name],
            cwd=WORKING_DIR,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
            check=True,
        )

    except subprocess.CalledProcessError as error:
        raise RuntimeError(
            f"XFOIL execution failed with exit code "
            f"{error.returncode}."
        ) from error

    return read_xfoil_output()


# =============================================================================
# XFOIL optimization problem
# =============================================================================

class XFOILProblem(RealProblem):
    """
    HQGA optimization problem based on XFOIL.

    The objective is to minimize the drag coefficient CD.
    """

    def __init__(
        self,
        dim=6,
        num_bit_code=4,
        lower_bounds=None,
        upper_bounds=None,
    ):

        if lower_bounds is None:
            lower_bounds = [-0.5] * dim

        if upper_bounds is None:
            upper_bounds = [0.5] * dim

        super().__init__(
            "xfoil",
            dim,
            num_bit_code,
            lower_bounds,
            upper_bounds,
        )

        self.name = "xfoil"

    def computeFitness(self, chromosome):
        """
        Evaluate one chromosome using XFOIL.
        """

        # Generate the input file for the current chromosome.
        write_xfoil_input(chromosome)

        # Run XFOIL and return the drag coefficient.
        return run_xfoil()


# =============================================================================
# Quantum backend
# =============================================================================

def create_backend():
    """
    Create the noisy simulator based on the IBM Brisbane device.
    """

    reference_backend = FakeBrisbane()

    return AerSimulator.from_backend(
        reference_backend,
        method="matrix_product_state",
    )


backend = create_backend()
device_features = hqga_utils.device(backend)


# =============================================================================
# HQGA execution
# =============================================================================

def run_hqga(
    problem,
    population_size,
    max_generations,
    delta,
    mu,
    elitism,
    rho,
):
    """
    Execute one HQGA run.

    Returns
    -------
    dict
        Results required for the experiment dataset.
    """

    # Reinforcement elitism uses a specific parameter class
    # that includes rho.
    if elitism == hqga_utils.ELITISM_R:

        parameters = hqga_utils.ReinforcementParameters(
            population_size,
            max_generations,
            delta,
            rho,
            mu,
        )

    else:

        parameters = hqga_utils.Parameters(
            population_size,
            max_generations,
            delta,
            mu,
            elitism,
        )

    # Disable interactive output.
    parameters.progressBar = False
    parameters.verbose = False
    parameters.draw_circuit = False

    # Create the quantum circuit.
    circuit = hqga_utils.setupCircuit(
        parameters.pop_size,
        problem.dim * problem.num_bit_code,
    )

    (
        global_best,
        chromosome_evolution,
        bests,
        fitness_history,
        best_individuals_per_generation,
        all_populations_per_generation,
    ) = hqga_algorithm.runQGA(
        device_features,
        circuit,
        parameters,
        problem,
    )

    # Only the quantities required in the final dataset are retained.
    return {
        "best_fitness": global_best.fitness,
        "best_phenotype": global_best.phenotype,
        "fitness_history": fitness_history,
    }


# =============================================================================
# Results management
# =============================================================================

def build_results_row(combination, runs_results):
    """
    Create one dataset row from all runs of a parameter combination.

    The dataset stores the complete results of the individual runs for:
        - final best fitness
        - final best phenotype
        - fitness history

    No additional aggregate metrics are calculated.
    """

    best_fitness_values = [
        run["best_fitness"]
        for run in runs_results
    ]

    best_phenotypes = [
        run["best_phenotype"]
        for run in runs_results
    ]

    fitness_histories = [
        run["fitness_history"]
        for run in runs_results
    ]

    return {
        # ---------------------------------------------------------------------
        # HQGA configuration
        # ---------------------------------------------------------------------
        "combination_id": combination["combination_id"],
        "pop_size": combination["pop_size"],
        "max_generations": combination["max_generations"],
        "b": combination["b"],
        "delta": round(combination["delta"], 2),
        "mu": combination["mu"],
        "elitism": combination["elitism"],
        "rho": round(combination["rho"], 2),

        # ---------------------------------------------------------------------
        # Results from individual runs
        # ---------------------------------------------------------------------
        "best_fitness_list": best_fitness_values,
        "best_phenotype_list": best_phenotypes,
        "fitness_history_list": fitness_histories,
    }


def save_results(results_df, filename):
    """
    Save the results in pickle and CSV formats.

    Pickle preserves Python data structures such as lists, while CSV
    provides a human-readable representation.
    """

    pickle_path = WORKING_DIR / f"{filename}.pkl"
    csv_path = WORKING_DIR / f"{filename}.csv"

    # Pickle preserves the original Python data structures.
    results_df.to_pickle(pickle_path)

    # CSV is provided for human-readable inspection.
    results_df.to_csv(csv_path, index=False)

    print("Results saved to:")
    print(f"  - {pickle_path}")
    print(f"  - {csv_path}")


# =============================================================================
# Experiment configuration
# =============================================================================

def generate_combinations():
    """
    Generate all HQGA parameter combinations used in the experiment.
    """

    combinations = []
    combination_id = 0

    for population_size in POPULATION_SIZES:

        for max_generations in MAX_GENERATIONS:

            for bit_length in BIT_LENGTHS:

                for delta in DELTA_VALUES:

                    for mu in MU_VALUES:

                        for elitism in ELITISM_METHODS:

                            # Reinforcement elitism uses the rho parameter.
                            if elitism == hqga_utils.ELITISM_R:
                                rho_values = RHO_VALUES

                            # For the other elitism methods rho is not used.
                            else:
                                rho_values = [0]

                            for rho in rho_values:

                                combinations.append(
                                    {
                                        "combination_id": combination_id,
                                        "pop_size": population_size,
                                        "max_generations": max_generations,
                                        "b": bit_length,
                                        "delta": delta,
                                        "mu": mu,
                                        "elitism": elitism,
                                        "rho": rho,
                                    }
                                )

                                combination_id += 1

    return combinations


# =============================================================================
# Main experiment
# =============================================================================

def main():
    """
    Run the complete HQGA experiment.
    """

    combinations = generate_combinations()

    print(
        f"Total parameter combinations: "
        f"{len(combinations)}"
    )

    results_df = pd.DataFrame()

    # Select the combinations to execute.
    combinations_to_run = combinations[START_COMBINATION:]

    for experiment_number, combination in enumerate(
        combinations_to_run,
        start=START_COMBINATION + 1,
    ):

        combination_id = combination["combination_id"]

        print("\n" + "=" * 80)

        print(
            f"Combination {experiment_number}/"
            f"{len(combinations)} "
            f"(ID: {combination_id})"
        )

        print(
            f"Population size: "
            f"{combination['pop_size']}"
        )

        print(
            f"Maximum generations: "
            f"{combination['max_generations']}"
        )

        print(
            f"Bits per variable: "
            f"{combination['b']}"
        )

        print(
            f"Delta: "
            f"{combination['delta']:.4f}"
        )

        print(
            f"Mu: "
            f"{combination['mu']}"
        )

        print(
            f"Elitism: "
            f"{combination['elitism']}"
        )

        print(
            f"Rho: "
            f"{combination['rho']:.4f}"
        )

        # Create the optimization problem.
        problem = XFOILProblem(
            num_bit_code=combination["b"]
        )

        runs_results = []

        # Execute independent runs.
        for run_id in range(N_RUNS):

            print(
                f"  Run {run_id + 1}/{N_RUNS}"
            )

            result = run_hqga(
                problem=problem,
                population_size=combination["pop_size"],
                max_generations=combination["max_generations"],
                delta=combination["delta"],
                mu=combination["mu"],
                elitism=combination["elitism"],
                rho=combination["rho"],
            )

            runs_results.append(result)

        # Build one row containing the results of all runs.
        results_row = build_results_row(
            combination,
            runs_results,
        )

        results_df = pd.concat(
            [
                results_df,
                pd.DataFrame([results_row]),
            ],
            ignore_index=True,
        )

        print(
            f"\nCombination {combination_id} completed."
        )

        # Save after every completed configuration.
        # This prevents the loss of previously completed results
        # if the experiment is interrupted.
        save_results(
            results_df,
            RESULTS_FILENAME,
        )


# =============================================================================
# Script entry point
# =============================================================================

if __name__ == "__main__":
    main()
